### ISSUE TITLE
Questions about equations in code

### ISSUE THREAD

**Issue by glugeorge** [aarobel/SSAsimpleM#1]
Hi Alex @aarobel,
I thought I would use this issues format to track some questions in an open manner - Jonny and I have used this for discussions and found it quite nice. 

I just had some clarifications/confusion with the code that I was hoping you could help me work through:
First here: 
https://github.com/aarobel/SSAsimpleM/blob/de1c9e450e9a47e898f1ca1770b7ae804e213e6b/SSA_simple.m#L142
I interpreted this to be analogous to equation A16 in Schoof (2007):
<img width="265" alt="image" src="https://user-images.githubusercontent.com/25989736/189375299-46545584-2084-4bee-a74a-7ab1e0bd8b17.png">
Is there a reason why we subtract a instead of adding it in the script?

Also here:
https://github.com/aarobel/SSAsimpleM/blob/de1c9e450e9a47e898f1ca1770b7ae804e213e6b/SSA_simple.m#L152
I see this is pretty much analogous to equation A18:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/25989736/189375648-e596e6c7-7fe2-4b2f-8c05-45fc0dd20e09.png">
However, for these to match, should that last h(N1+1) term also have a 0.5 multiplier?

I ask these clarifications because I think the rest of the equations are the same as the ones in Schoof's paper, and if I make these modifications I detailed above, the solver doesn't seem to find a solution. Would love to hear your thoughts on this!

Thanks,
George Lu

**Comment by aarobel** [comment]
So, these are actually errors in the appendix to Christian's paper. For example if you think of where A16 comes from, a is the SMB, which comes over from the RHS where it is positive, so it should be negative on the LHS. For the second,  the 1/2 comes from the staggered grid and how extrapolation is done.

I wasn't clear whether you were saying that it doesn't converge if you use my equations or Christian's equations. I know that my version of the model converges in MATLAB at least.

**Comment by glugeorge** [comment]
Ah, I see, thanks for this clarification! And thanks for the explanations of these errors in the appendix, I will try to follow the equations more closely. 

Yes, your model works fine in MATLAB. 

As an aside, I was wondering if you remember any potential issues with the solver returning "solver stalled" or "potential inaccuracies" when decreasing the time step size? I noticed that it doesn't really impact the solution, but it'd be neat to unpack why. I'm supposing it's due to the size of the time scale. For reference, I am trying to couple this with my hydrology model, but the hydrology operates on a much finer time scale to the point where I'm unable to realistically simulate any kind of hydrology transience when coupling with the ice. 

Thanks again!

**Comment by aarobel** [comment]
For very short time steps you may need to modify some of the solution tolerances, since the time derivative term is going to dominate the other terms. My student has run a version of this model (for tidewater glaciers, but with the same general solution method in MATLAB) at a daily time step with no problem. I imagine you may be running it at even shorter time step, which may require messing with the solver tolerances.
